using System;
using System.Runtime.InteropServices;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Layouts;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

namespace Minis
{
    [Flags]
    public enum MidiPlaybackButton : byte
    {
        None = 0,

        Start = 1 << 0,
        Continue = 1 << 1,
        Stop = 1 << 2,
    }

    /// <summary>
    /// The state format used for a MIDI device.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct MidiDeviceState : IInputStateTypeInfo
    {
        public const int NoteOffset = 0;
        public const int NoteCount = 128;

        public const int CcOffset = NoteOffset + NoteCount;
        public const int CcCount = 120;

        public const int PitchBendOffset = CcOffset + CcCount;
        public const int PitchBendSize = sizeof(ushort);

        public const int ChannelPressureOffset = PitchBendOffset + PitchBendSize;
        public const int ChannelPressureSize = sizeof(byte);

        public const int PlaybackButtonsOffset = ChannelPressureOffset + ChannelPressureSize;
        public const int PlaybackButtonsSize = sizeof(byte);

        public static readonly FourCC Format = new FourCC('M', 'I', 'D', 'J');
        public FourCC format => Format;

        [InputControl(name = "note000", displayName = "Note 000 (C-1)",  shortDisplayName = "C-1",  layout = "MidiButton", offset = 0)]
        [InputControl(name = "note001", displayName = "Note 001 (C#-1)", shortDisplayName = "C#-1", layout = "MidiButton", offset = 1)]
        [InputControl(name = "note002", displayName = "Note 002 (D-1)",  shortDisplayName = "D-1",  layout = "MidiButton", offset = 2)]
        [InputControl(name = "note003", displayName = "Note 003 (D#-1)", shortDisplayName = "D#-1", layout = "MidiButton", offset = 3)]
        [InputControl(name = "note004", displayName = "Note 004 (E-1)",  shortDisplayName = "E-1",  layout = "MidiButton", offset = 4)]
        [InputControl(name = "note005", displayName = "Note 005 (F-1)",  shortDisplayName = "F-1",  layout = "MidiButton", offset = 5)]
        [InputControl(name = "note006", displayName = "Note 006 (F#-1)", shortDisplayName = "F#-1", layout = "MidiButton", offset = 6)]
        [InputControl(name = "note007", displayName = "Note 007 (G-1)",  shortDisplayName = "G-1",  layout = "MidiButton", offset = 7)]
        [InputControl(name = "note008", displayName = "Note 008 (G#-1)", shortDisplayName = "G#-1", layout = "MidiButton", offset = 8)]
        [InputControl(name = "note009", displayName = "Note 009 (A-1)",  shortDisplayName = "A-1",  layout = "MidiButton", offset = 9)]
        [InputControl(name = "note010", displayName = "Note 010 (A#-1)", shortDisplayName = "A#-1", layout = "MidiButton", offset = 10)]
        [InputControl(name = "note011", displayName = "Note 011 (B-1)",  shortDisplayName = "B-1",  layout = "MidiButton", offset = 11)]
        [InputControl(name = "note012", displayName = "Note 012 (C0)",   shortDisplayName = "C0",   layout = "MidiButton", offset = 12)]
        [InputControl(name = "note013", displayName = "Note 013 (C#0)",  shortDisplayName = "C#0",  layout = "MidiButton", offset = 13)]
        [InputControl(name = "note014", displayName = "Note 014 (D0)",   shortDisplayName = "D0",   layout = "MidiButton", offset = 14)]
        [InputControl(name = "note015", displayName = "Note 015 (D#0)",  shortDisplayName = "D#0",  layout = "MidiButton", offset = 15)]
        [InputControl(name = "note016", displayName = "Note 016 (E0)",   shortDisplayName = "E0",   layout = "MidiButton", offset = 16)]
        [InputControl(name = "note017", displayName = "Note 017 (F0)",   shortDisplayName = "F0",   layout = "MidiButton", offset = 17)]
        [InputControl(name = "note018", displayName = "Note 018 (F#0)",  shortDisplayName = "F#0",  layout = "MidiButton", offset = 18)]
        [InputControl(name = "note019", displayName = "Note 019 (G0)",   shortDisplayName = "G0",   layout = "MidiButton", offset = 19)]
        [InputControl(name = "note020", displayName = "Note 020 (G#0)",  shortDisplayName = "G#0",  layout = "MidiButton", offset = 20)]
        [InputControl(name = "note021", displayName = "Note 021 (A0)",   shortDisplayName = "A0",   layout = "MidiButton", offset = 21)]
        [InputControl(name = "note022", displayName = "Note 022 (A#0)",  shortDisplayName = "A#0",  layout = "MidiButton", offset = 22)]
        [InputControl(name = "note023", displayName = "Note 023 (B0)",   shortDisplayName = "B0",   layout = "MidiButton", offset = 23)]
        [InputControl(name = "note024", displayName = "Note 024 (C1)",   shortDisplayName = "C1",   layout = "MidiButton", offset = 24)]
        [InputControl(name = "note025", displayName = "Note 025 (C#1)",  shortDisplayName = "C#1",  layout = "MidiButton", offset = 25)]
        [InputControl(name = "note026", displayName = "Note 026 (D1)",   shortDisplayName = "D1",   layout = "MidiButton", offset = 26)]
        [InputControl(name = "note027", displayName = "Note 027 (D#1)",  shortDisplayName = "D#1",  layout = "MidiButton", offset = 27)]
        [InputControl(name = "note028", displayName = "Note 028 (E1)",   shortDisplayName = "E1",   layout = "MidiButton", offset = 28)]
        [InputControl(name = "note029", displayName = "Note 029 (F1)",   shortDisplayName = "F1",   layout = "MidiButton", offset = 29)]
        [InputControl(name = "note030", displayName = "Note 030 (F#1)",  shortDisplayName = "F#1",  layout = "MidiButton", offset = 30)]
        [InputControl(name = "note031", displayName = "Note 031 (G1)",   shortDisplayName = "G1",   layout = "MidiButton", offset = 31)]
        [InputControl(name = "note032", displayName = "Note 032 (G#1)",  shortDisplayName = "G#1",  layout = "MidiButton", offset = 32)]
        [InputControl(name = "note033", displayName = "Note 033 (A1)",   shortDisplayName = "A1",   layout = "MidiButton", offset = 33)]
        [InputControl(name = "note034", displayName = "Note 034 (A#1)",  shortDisplayName = "A#1",  layout = "MidiButton", offset = 34)]
        [InputControl(name = "note035", displayName = "Note 035 (B1)",   shortDisplayName = "B1",   layout = "MidiButton", offset = 35)]
        [InputControl(name = "note036", displayName = "Note 036 (C2)",   shortDisplayName = "C2",   layout = "MidiButton", offset = 36)]
        [InputControl(name = "note037", displayName = "Note 037 (C#2)",  shortDisplayName = "C#2",  layout = "MidiButton", offset = 37)]
        [InputControl(name = "note038", displayName = "Note 038 (D2)",   shortDisplayName = "D2",   layout = "MidiButton", offset = 38)]
        [InputControl(name = "note039", displayName = "Note 039 (D#2)",  shortDisplayName = "D#2",  layout = "MidiButton", offset = 39)]
        [InputControl(name = "note040", displayName = "Note 040 (E2)",   shortDisplayName = "E2",   layout = "MidiButton", offset = 40)]
        [InputControl(name = "note041", displayName = "Note 041 (F2)",   shortDisplayName = "F2",   layout = "MidiButton", offset = 41)]
        [InputControl(name = "note042", displayName = "Note 042 (F#2)",  shortDisplayName = "F#2",  layout = "MidiButton", offset = 42)]
        [InputControl(name = "note043", displayName = "Note 043 (G2)",   shortDisplayName = "G2",   layout = "MidiButton", offset = 43)]
        [InputControl(name = "note044", displayName = "Note 044 (G#2)",  shortDisplayName = "G#2",  layout = "MidiButton", offset = 44)]
        [InputControl(name = "note045", displayName = "Note 045 (A2)",   shortDisplayName = "A2",   layout = "MidiButton", offset = 45)]
        [InputControl(name = "note046", displayName = "Note 046 (A#2)",  shortDisplayName = "A#2",  layout = "MidiButton", offset = 46)]
        [InputControl(name = "note047", displayName = "Note 047 (B2)",   shortDisplayName = "B2",   layout = "MidiButton", offset = 47)]
        [InputControl(name = "note048", displayName = "Note 048 (C3)",   shortDisplayName = "C3",   layout = "MidiButton", offset = 48)]
        [InputControl(name = "note049", displayName = "Note 049 (C#3)",  shortDisplayName = "C#3",  layout = "MidiButton", offset = 49)]
        [InputControl(name = "note050", displayName = "Note 050 (D3)",   shortDisplayName = "D3",   layout = "MidiButton", offset = 50)]
        [InputControl(name = "note051", displayName = "Note 051 (D#3)",  shortDisplayName = "D#3",  layout = "MidiButton", offset = 51)]
        [InputControl(name = "note052", displayName = "Note 052 (E3)",   shortDisplayName = "E3",   layout = "MidiButton", offset = 52)]
        [InputControl(name = "note053", displayName = "Note 053 (F3)",   shortDisplayName = "F3",   layout = "MidiButton", offset = 53)]
        [InputControl(name = "note054", displayName = "Note 054 (F#3)",  shortDisplayName = "F#3",  layout = "MidiButton", offset = 54)]
        [InputControl(name = "note055", displayName = "Note 055 (G3)",   shortDisplayName = "G3",   layout = "MidiButton", offset = 55)]
        [InputControl(name = "note056", displayName = "Note 056 (G#3)",  shortDisplayName = "G#3",  layout = "MidiButton", offset = 56)]
        [InputControl(name = "note057", displayName = "Note 057 (A3)",   shortDisplayName = "A3",   layout = "MidiButton", offset = 57)]
        [InputControl(name = "note058", displayName = "Note 058 (A#3)",  shortDisplayName = "A#3",  layout = "MidiButton", offset = 58)]
        [InputControl(name = "note059", displayName = "Note 059 (B3)",   shortDisplayName = "B3",   layout = "MidiButton", offset = 59)]
        [InputControl(name = "note060", displayName = "Note 060 (C4)",   shortDisplayName = "C4",   layout = "MidiButton", offset = 60)]
        [InputControl(name = "note061", displayName = "Note 061 (C#4)",  shortDisplayName = "C#4",  layout = "MidiButton", offset = 61)]
        [InputControl(name = "note062", displayName = "Note 062 (D4)",   shortDisplayName = "D4",   layout = "MidiButton", offset = 62)]
        [InputControl(name = "note063", displayName = "Note 063 (D#4)",  shortDisplayName = "D#4",  layout = "MidiButton", offset = 63)]
        [InputControl(name = "note064", displayName = "Note 064 (E4)",   shortDisplayName = "E4",   layout = "MidiButton", offset = 64)]
        [InputControl(name = "note065", displayName = "Note 065 (F4)",   shortDisplayName = "F4",   layout = "MidiButton", offset = 65)]
        [InputControl(name = "note066", displayName = "Note 066 (F#4)",  shortDisplayName = "F#4",  layout = "MidiButton", offset = 66)]
        [InputControl(name = "note067", displayName = "Note 067 (G4)",   shortDisplayName = "G4",   layout = "MidiButton", offset = 67)]
        [InputControl(name = "note068", displayName = "Note 068 (G#4)",  shortDisplayName = "G#4",  layout = "MidiButton", offset = 68)]
        [InputControl(name = "note069", displayName = "Note 069 (A4)",   shortDisplayName = "A4",   layout = "MidiButton", offset = 69)]
        [InputControl(name = "note070", displayName = "Note 070 (A#4)",  shortDisplayName = "A#4",  layout = "MidiButton", offset = 70)]
        [InputControl(name = "note071", displayName = "Note 071 (B4)",   shortDisplayName = "B4",   layout = "MidiButton", offset = 71)]
        [InputControl(name = "note072", displayName = "Note 072 (C5)",   shortDisplayName = "C5",   layout = "MidiButton", offset = 72)]
        [InputControl(name = "note073", displayName = "Note 073 (C#5)",  shortDisplayName = "C#5",  layout = "MidiButton", offset = 73)]
        [InputControl(name = "note074", displayName = "Note 074 (D5)",   shortDisplayName = "D5",   layout = "MidiButton", offset = 74)]
        [InputControl(name = "note075", displayName = "Note 075 (D#5)",  shortDisplayName = "D#5",  layout = "MidiButton", offset = 75)]
        [InputControl(name = "note076", displayName = "Note 076 (E5)",   shortDisplayName = "E5",   layout = "MidiButton", offset = 76)]
        [InputControl(name = "note077", displayName = "Note 077 (F5)",   shortDisplayName = "F5",   layout = "MidiButton", offset = 77)]
        [InputControl(name = "note078", displayName = "Note 078 (F#5)",  shortDisplayName = "F#5",  layout = "MidiButton", offset = 78)]
        [InputControl(name = "note079", displayName = "Note 079 (G5)",   shortDisplayName = "G5",   layout = "MidiButton", offset = 79)]
        [InputControl(name = "note080", displayName = "Note 080 (G#5)",  shortDisplayName = "G#5",  layout = "MidiButton", offset = 80)]
        [InputControl(name = "note081", displayName = "Note 081 (A5)",   shortDisplayName = "A5",   layout = "MidiButton", offset = 81)]
        [InputControl(name = "note082", displayName = "Note 082 (A#5)",  shortDisplayName = "A#5",  layout = "MidiButton", offset = 82)]
        [InputControl(name = "note083", displayName = "Note 083 (B5)",   shortDisplayName = "B5",   layout = "MidiButton", offset = 83)]
        [InputControl(name = "note084", displayName = "Note 084 (C6)",   shortDisplayName = "C6",   layout = "MidiButton", offset = 84)]
        [InputControl(name = "note085", displayName = "Note 085 (C#6)",  shortDisplayName = "C#6",  layout = "MidiButton", offset = 85)]
        [InputControl(name = "note086", displayName = "Note 086 (D6)",   shortDisplayName = "D6",   layout = "MidiButton", offset = 86)]
        [InputControl(name = "note087", displayName = "Note 087 (D#6)",  shortDisplayName = "D#6",  layout = "MidiButton", offset = 87)]
        [InputControl(name = "note088", displayName = "Note 088 (E6)",   shortDisplayName = "E6",   layout = "MidiButton", offset = 88)]
        [InputControl(name = "note089", displayName = "Note 089 (F6)",   shortDisplayName = "F6",   layout = "MidiButton", offset = 89)]
        [InputControl(name = "note090", displayName = "Note 090 (F#6)",  shortDisplayName = "F#6",  layout = "MidiButton", offset = 90)]
        [InputControl(name = "note091", displayName = "Note 091 (G6)",   shortDisplayName = "G6",   layout = "MidiButton", offset = 91)]
        [InputControl(name = "note092", displayName = "Note 092 (G#6)",  shortDisplayName = "G#6",  layout = "MidiButton", offset = 92)]
        [InputControl(name = "note093", displayName = "Note 093 (A6)",   shortDisplayName = "A6",   layout = "MidiButton", offset = 93)]
        [InputControl(name = "note094", displayName = "Note 094 (A#6)",  shortDisplayName = "A#6",  layout = "MidiButton", offset = 94)]
        [InputControl(name = "note095", displayName = "Note 095 (B6)",   shortDisplayName = "B6",   layout = "MidiButton", offset = 95)]
        [InputControl(name = "note096", displayName = "Note 096 (C7)",   shortDisplayName = "C7",   layout = "MidiButton", offset = 96)]
        [InputControl(name = "note097", displayName = "Note 097 (C#7)",  shortDisplayName = "C#7",  layout = "MidiButton", offset = 97)]
        [InputControl(name = "note098", displayName = "Note 098 (D7)",   shortDisplayName = "D7",   layout = "MidiButton", offset = 98)]
        [InputControl(name = "note099", displayName = "Note 099 (D#7)",  shortDisplayName = "D#7",  layout = "MidiButton", offset = 99)]
        [InputControl(name = "note100", displayName = "Note 100 (E7)",   shortDisplayName = "E7",   layout = "MidiButton", offset = 100)]
        [InputControl(name = "note101", displayName = "Note 101 (F7)",   shortDisplayName = "F7",   layout = "MidiButton", offset = 101)]
        [InputControl(name = "note102", displayName = "Note 102 (F#7)",  shortDisplayName = "F#7",  layout = "MidiButton", offset = 102)]
        [InputControl(name = "note103", displayName = "Note 103 (G7)",   shortDisplayName = "G7",   layout = "MidiButton", offset = 103)]
        [InputControl(name = "note104", displayName = "Note 104 (G#7)",  shortDisplayName = "G#7",  layout = "MidiButton", offset = 104)]
        [InputControl(name = "note105", displayName = "Note 105 (A7)",   shortDisplayName = "A7",   layout = "MidiButton", offset = 105)]
        [InputControl(name = "note106", displayName = "Note 106 (A#7)",  shortDisplayName = "A#7",  layout = "MidiButton", offset = 106)]
        [InputControl(name = "note107", displayName = "Note 107 (B7)",   shortDisplayName = "B7",   layout = "MidiButton", offset = 107)]
        [InputControl(name = "note108", displayName = "Note 108 (C8)",   shortDisplayName = "C8",   layout = "MidiButton", offset = 108)]
        [InputControl(name = "note109", displayName = "Note 109 (C#8)",  shortDisplayName = "C#8",  layout = "MidiButton", offset = 109)]
        [InputControl(name = "note110", displayName = "Note 110 (D8)",   shortDisplayName = "D8",   layout = "MidiButton", offset = 110)]
        [InputControl(name = "note111", displayName = "Note 111 (D#8)",  shortDisplayName = "D#8",  layout = "MidiButton", offset = 111)]
        [InputControl(name = "note112", displayName = "Note 112 (E8)",   shortDisplayName = "E8",   layout = "MidiButton", offset = 112)]
        [InputControl(name = "note113", displayName = "Note 113 (F8)",   shortDisplayName = "F8",   layout = "MidiButton", offset = 113)]
        [InputControl(name = "note114", displayName = "Note 114 (F#8)",  shortDisplayName = "F#8",  layout = "MidiButton", offset = 114)]
        [InputControl(name = "note115", displayName = "Note 115 (G8)",   shortDisplayName = "G8",   layout = "MidiButton", offset = 115)]
        [InputControl(name = "note116", displayName = "Note 116 (G#8)",  shortDisplayName = "G#8",  layout = "MidiButton", offset = 116)]
        [InputControl(name = "note117", displayName = "Note 117 (A8)",   shortDisplayName = "A8",   layout = "MidiButton", offset = 117)]
        [InputControl(name = "note118", displayName = "Note 118 (A#8)",  shortDisplayName = "A#8",  layout = "MidiButton", offset = 118)]
        [InputControl(name = "note119", displayName = "Note 119 (B8)",   shortDisplayName = "B8",   layout = "MidiButton", offset = 119)]
        [InputControl(name = "note120", displayName = "Note 120 (C9)",   shortDisplayName = "C9",   layout = "MidiButton", offset = 120)]
        [InputControl(name = "note121", displayName = "Note 121 (C#9)",  shortDisplayName = "C#9",  layout = "MidiButton", offset = 121)]
        [InputControl(name = "note122", displayName = "Note 122 (D9)",   shortDisplayName = "D9",   layout = "MidiButton", offset = 122)]
        [InputControl(name = "note123", displayName = "Note 123 (D#9)",  shortDisplayName = "D#9",  layout = "MidiButton", offset = 123)]
        [InputControl(name = "note124", displayName = "Note 124 (E9)",   shortDisplayName = "E9",   layout = "MidiButton", offset = 124)]
        [InputControl(name = "note125", displayName = "Note 125 (F9)",   shortDisplayName = "F9",   layout = "MidiButton", offset = 125)]
        [InputControl(name = "note126", displayName = "Note 126 (F#9)",  shortDisplayName = "F#9",  layout = "MidiButton", offset = 126)]
        [InputControl(name = "note127", displayName = "Note 127 (G9)",   shortDisplayName = "G9",   layout = "MidiButton", offset = 127)]
        public fixed byte notes[128];

        [InputControl(name = "cc000", displayName = "CC 0",   layout = "MidiAxis", offset = 128)]
        [InputControl(name = "cc001", displayName = "CC 1",   layout = "MidiAxis", offset = 129)]
        [InputControl(name = "cc002", displayName = "CC 2",   layout = "MidiAxis", offset = 130)]
        [InputControl(name = "cc003", displayName = "CC 3",   layout = "MidiAxis", offset = 131)]
        [InputControl(name = "cc004", displayName = "CC 4",   layout = "MidiAxis", offset = 132)]
        [InputControl(name = "cc005", displayName = "CC 5",   layout = "MidiAxis", offset = 133)]
        [InputControl(name = "cc006", displayName = "CC 6",   layout = "MidiAxis", offset = 134)]
        [InputControl(name = "cc007", displayName = "CC 7",   layout = "MidiAxis", offset = 135)]
        [InputControl(name = "cc008", displayName = "CC 8",   layout = "MidiAxis", offset = 136)]
        [InputControl(name = "cc009", displayName = "CC 9",   layout = "MidiAxis", offset = 137)]
        [InputControl(name = "cc010", displayName = "CC 10",  layout = "MidiAxis", offset = 138)]
        [InputControl(name = "cc011", displayName = "CC 11",  layout = "MidiAxis", offset = 139)]
        [InputControl(name = "cc012", displayName = "CC 12",  layout = "MidiAxis", offset = 140)]
        [InputControl(name = "cc013", displayName = "CC 13",  layout = "MidiAxis", offset = 141)]
        [InputControl(name = "cc014", displayName = "CC 14",  layout = "MidiAxis", offset = 142)]
        [InputControl(name = "cc015", displayName = "CC 15",  layout = "MidiAxis", offset = 143)]
        [InputControl(name = "cc016", displayName = "CC 16",  layout = "MidiAxis", offset = 144)]
        [InputControl(name = "cc017", displayName = "CC 17",  layout = "MidiAxis", offset = 145)]
        [InputControl(name = "cc018", displayName = "CC 18",  layout = "MidiAxis", offset = 146)]
        [InputControl(name = "cc019", displayName = "CC 19",  layout = "MidiAxis", offset = 147)]
        [InputControl(name = "cc020", displayName = "CC 20",  layout = "MidiAxis", offset = 148)]
        [InputControl(name = "cc021", displayName = "CC 21",  layout = "MidiAxis", offset = 149)]
        [InputControl(name = "cc022", displayName = "CC 22",  layout = "MidiAxis", offset = 150)]
        [InputControl(name = "cc023", displayName = "CC 23",  layout = "MidiAxis", offset = 151)]
        [InputControl(name = "cc024", displayName = "CC 24",  layout = "MidiAxis", offset = 152)]
        [InputControl(name = "cc025", displayName = "CC 25",  layout = "MidiAxis", offset = 153)]
        [InputControl(name = "cc026", displayName = "CC 26",  layout = "MidiAxis", offset = 154)]
        [InputControl(name = "cc027", displayName = "CC 27",  layout = "MidiAxis", offset = 155)]
        [InputControl(name = "cc028", displayName = "CC 28",  layout = "MidiAxis", offset = 156)]
        [InputControl(name = "cc029", displayName = "CC 29",  layout = "MidiAxis", offset = 157)]
        [InputControl(name = "cc030", displayName = "CC 30",  layout = "MidiAxis", offset = 158)]
        [InputControl(name = "cc031", displayName = "CC 31",  layout = "MidiAxis", offset = 159)]
        [InputControl(name = "cc032", displayName = "CC 32",  layout = "MidiAxis", offset = 160)]
        [InputControl(name = "cc033", displayName = "CC 33",  layout = "MidiAxis", offset = 161)]
        [InputControl(name = "cc034", displayName = "CC 34",  layout = "MidiAxis", offset = 162)]
        [InputControl(name = "cc035", displayName = "CC 35",  layout = "MidiAxis", offset = 163)]
        [InputControl(name = "cc036", displayName = "CC 36",  layout = "MidiAxis", offset = 164)]
        [InputControl(name = "cc037", displayName = "CC 37",  layout = "MidiAxis", offset = 165)]
        [InputControl(name = "cc038", displayName = "CC 38",  layout = "MidiAxis", offset = 166)]
        [InputControl(name = "cc039", displayName = "CC 39",  layout = "MidiAxis", offset = 167)]
        [InputControl(name = "cc040", displayName = "CC 40",  layout = "MidiAxis", offset = 168)]
        [InputControl(name = "cc041", displayName = "CC 41",  layout = "MidiAxis", offset = 169)]
        [InputControl(name = "cc042", displayName = "CC 42",  layout = "MidiAxis", offset = 170)]
        [InputControl(name = "cc043", displayName = "CC 43",  layout = "MidiAxis", offset = 171)]
        [InputControl(name = "cc044", displayName = "CC 44",  layout = "MidiAxis", offset = 172)]
        [InputControl(name = "cc045", displayName = "CC 45",  layout = "MidiAxis", offset = 173)]
        [InputControl(name = "cc046", displayName = "CC 46",  layout = "MidiAxis", offset = 174)]
        [InputControl(name = "cc047", displayName = "CC 47",  layout = "MidiAxis", offset = 175)]
        [InputControl(name = "cc048", displayName = "CC 48",  layout = "MidiAxis", offset = 176)]
        [InputControl(name = "cc049", displayName = "CC 49",  layout = "MidiAxis", offset = 177)]
        [InputControl(name = "cc050", displayName = "CC 50",  layout = "MidiAxis", offset = 178)]
        [InputControl(name = "cc051", displayName = "CC 51",  layout = "MidiAxis", offset = 179)]
        [InputControl(name = "cc052", displayName = "CC 52",  layout = "MidiAxis", offset = 180)]
        [InputControl(name = "cc053", displayName = "CC 53",  layout = "MidiAxis", offset = 181)]
        [InputControl(name = "cc054", displayName = "CC 54",  layout = "MidiAxis", offset = 182)]
        [InputControl(name = "cc055", displayName = "CC 55",  layout = "MidiAxis", offset = 183)]
        [InputControl(name = "cc056", displayName = "CC 56",  layout = "MidiAxis", offset = 184)]
        [InputControl(name = "cc057", displayName = "CC 57",  layout = "MidiAxis", offset = 185)]
        [InputControl(name = "cc058", displayName = "CC 58",  layout = "MidiAxis", offset = 186)]
        [InputControl(name = "cc059", displayName = "CC 59",  layout = "MidiAxis", offset = 187)]
        [InputControl(name = "cc060", displayName = "CC 60",  layout = "MidiAxis", offset = 188)]
        [InputControl(name = "cc061", displayName = "CC 61",  layout = "MidiAxis", offset = 189)]
        [InputControl(name = "cc062", displayName = "CC 62",  layout = "MidiAxis", offset = 190)]
        [InputControl(name = "cc063", displayName = "CC 63",  layout = "MidiAxis", offset = 191)]
        [InputControl(name = "cc064", displayName = "CC 64",  layout = "MidiAxis", offset = 192)]
        [InputControl(name = "cc065", displayName = "CC 65",  layout = "MidiAxis", offset = 193)]
        [InputControl(name = "cc066", displayName = "CC 66",  layout = "MidiAxis", offset = 194)]
        [InputControl(name = "cc067", displayName = "CC 67",  layout = "MidiAxis", offset = 195)]
        [InputControl(name = "cc068", displayName = "CC 68",  layout = "MidiAxis", offset = 196)]
        [InputControl(name = "cc069", displayName = "CC 69",  layout = "MidiAxis", offset = 197)]
        [InputControl(name = "cc070", displayName = "CC 70",  layout = "MidiAxis", offset = 198)]
        [InputControl(name = "cc071", displayName = "CC 71",  layout = "MidiAxis", offset = 199)]
        [InputControl(name = "cc072", displayName = "CC 72",  layout = "MidiAxis", offset = 200)]
        [InputControl(name = "cc073", displayName = "CC 73",  layout = "MidiAxis", offset = 201)]
        [InputControl(name = "cc074", displayName = "CC 74",  layout = "MidiAxis", offset = 202)]
        [InputControl(name = "cc075", displayName = "CC 75",  layout = "MidiAxis", offset = 203)]
        [InputControl(name = "cc076", displayName = "CC 76",  layout = "MidiAxis", offset = 204)]
        [InputControl(name = "cc077", displayName = "CC 77",  layout = "MidiAxis", offset = 205)]
        [InputControl(name = "cc078", displayName = "CC 78",  layout = "MidiAxis", offset = 206)]
        [InputControl(name = "cc079", displayName = "CC 79",  layout = "MidiAxis", offset = 207)]
        [InputControl(name = "cc080", displayName = "CC 80",  layout = "MidiAxis", offset = 208)]
        [InputControl(name = "cc081", displayName = "CC 81",  layout = "MidiAxis", offset = 209)]
        [InputControl(name = "cc082", displayName = "CC 82",  layout = "MidiAxis", offset = 210)]
        [InputControl(name = "cc083", displayName = "CC 83",  layout = "MidiAxis", offset = 211)]
        [InputControl(name = "cc084", displayName = "CC 84",  layout = "MidiAxis", offset = 212)]
        [InputControl(name = "cc085", displayName = "CC 85",  layout = "MidiAxis", offset = 213)]
        [InputControl(name = "cc086", displayName = "CC 86",  layout = "MidiAxis", offset = 214)]
        [InputControl(name = "cc087", displayName = "CC 87",  layout = "MidiAxis", offset = 215)]
        [InputControl(name = "cc088", displayName = "CC 88",  layout = "MidiAxis", offset = 216)]
        [InputControl(name = "cc089", displayName = "CC 89",  layout = "MidiAxis", offset = 217)]
        [InputControl(name = "cc090", displayName = "CC 90",  layout = "MidiAxis", offset = 218)]
        [InputControl(name = "cc091", displayName = "CC 91",  layout = "MidiAxis", offset = 219)]
        [InputControl(name = "cc092", displayName = "CC 92",  layout = "MidiAxis", offset = 220)]
        [InputControl(name = "cc093", displayName = "CC 93",  layout = "MidiAxis", offset = 221)]
        [InputControl(name = "cc094", displayName = "CC 94",  layout = "MidiAxis", offset = 222)]
        [InputControl(name = "cc095", displayName = "CC 95",  layout = "MidiAxis", offset = 223)]
        [InputControl(name = "cc096", displayName = "CC 96",  layout = "MidiAxis", offset = 224)]
        [InputControl(name = "cc097", displayName = "CC 97",  layout = "MidiAxis", offset = 225)]
        [InputControl(name = "cc098", displayName = "CC 98",  layout = "MidiAxis", offset = 226)]
        [InputControl(name = "cc099", displayName = "CC 99",  layout = "MidiAxis", offset = 227)]
        [InputControl(name = "cc100", displayName = "CC 100", layout = "MidiAxis", offset = 228)]
        [InputControl(name = "cc101", displayName = "CC 101", layout = "MidiAxis", offset = 229)]
        [InputControl(name = "cc102", displayName = "CC 102", layout = "MidiAxis", offset = 230)]
        [InputControl(name = "cc103", displayName = "CC 103", layout = "MidiAxis", offset = 231)]
        [InputControl(name = "cc104", displayName = "CC 104", layout = "MidiAxis", offset = 232)]
        [InputControl(name = "cc105", displayName = "CC 105", layout = "MidiAxis", offset = 233)]
        [InputControl(name = "cc106", displayName = "CC 106", layout = "MidiAxis", offset = 234)]
        [InputControl(name = "cc107", displayName = "CC 107", layout = "MidiAxis", offset = 235)]
        [InputControl(name = "cc108", displayName = "CC 108", layout = "MidiAxis", offset = 236)]
        [InputControl(name = "cc109", displayName = "CC 109", layout = "MidiAxis", offset = 237)]
        [InputControl(name = "cc110", displayName = "CC 110", layout = "MidiAxis", offset = 238)]
        [InputControl(name = "cc111", displayName = "CC 111", layout = "MidiAxis", offset = 239)]
        [InputControl(name = "cc112", displayName = "CC 112", layout = "MidiAxis", offset = 240)]
        [InputControl(name = "cc113", displayName = "CC 113", layout = "MidiAxis", offset = 241)]
        [InputControl(name = "cc114", displayName = "CC 114", layout = "MidiAxis", offset = 242)]
        [InputControl(name = "cc115", displayName = "CC 115", layout = "MidiAxis", offset = 243)]
        [InputControl(name = "cc116", displayName = "CC 116", layout = "MidiAxis", offset = 244)]
        [InputControl(name = "cc117", displayName = "CC 117", layout = "MidiAxis", offset = 245)]
        [InputControl(name = "cc118", displayName = "CC 118", layout = "MidiAxis", offset = 246)]
        [InputControl(name = "cc119", displayName = "CC 119", layout = "MidiAxis", offset = 247)]
        public fixed byte controls[120];

        // Format/size must be specified directly since the input system overrides it with the type of the field
        // [InputControl(name = "pitchBend", displayName = "Pitch Bend", shortDisplayName = "Pitch", layout = "MidiPitch", defaultState = (ushort)8192)]
        [InputControl(name = "pitchBend", displayName = "Pitch Bend", shortDisplayName = "P.Bend", layout = "MidiAxis", format = "BIT", sizeInBits = 14, parameters = "minValue=0,maxValue=16383,zeroPoint=8192", defaultState = (ushort)8192)]
        public ushort pitchBend;

        [InputControl(name = "channelPressure", displayName = "Channel Pressure", shortDisplayName = "Ch.Press", layout = "MidiAxis")]
        public byte channelPressure;

        [InputControl(name = "start",    displayName = "Start",    layout = "Button", bit = 0)]
        [InputControl(name = "continue", displayName = "Continue", layout = "Button", bit = 1)]
        [InputControl(name = "stop",     displayName = "Stop",     layout = "Button", bit = 2)]
        public byte playbackButtons;
    }
}
